package com.steeka.atmospot.persistence;

// Generated Mar 1, 2017 12:59:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Temperature generated by hbm2java
 */
@Entity
@Table(name = "temperature", schema = "public")
public class Temperature implements java.io.Serializable {

	private TemperatureId id;

	public Temperature() {
	}

	public Temperature(TemperatureId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "city", column = @Column(name = "city", nullable = false, length = 56)),
			@AttributeOverride(name = "tempLow", column = @Column(name = "temp_low", nullable = false)),
			@AttributeOverride(name = "tempHigh", column = @Column(name = "temp_high", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 13)) })
	public TemperatureId getId() {
		return this.id;
	}

	public void setId(TemperatureId id) {
		this.id = id;
	}

}
