package com.steeka.atmospot.persistence;

// Generated Mar 1, 2017 5:19:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Temperature generated by hbm2java
 */
@Entity
@Table(name = "temperature", schema = "public")
public class Temperature implements java.io.Serializable {

	private long tempId;
	private Date timestamp;
	private short temp;

	public Temperature() {
	}

	public Temperature(long tempId, short temp) {
		this.tempId = tempId;
		this.temp = temp;
	}

	@Id
	//@GeneratedValue(generator="increment")
	//@GenericGenerator(name="increment", strategy = "increment")
	@Column(name = "tempId", unique = true, nullable = false)
	public long getTempId() {
		return this.tempId;
	}

	public void setTempId(long tempId) {
		this.tempId = tempId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 35)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "temp", nullable = false)
	public short getTemp() {
		return this.temp;
	}

	public void setTemp(short temp) {
		this.temp = temp;
	}

}
