package com.steeka.atmospot.persistence;

// Generated Mar 1, 2017 12:59:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TemperatureId generated by hbm2java
 */
@Embeddable
public class TemperatureId implements java.io.Serializable {

	private String city;
	private short tempLow;
	private short tempHigh;
	private Date date;

	public TemperatureId() {
	}

	public TemperatureId(String city, short tempLow, short tempHigh, Date date) {
		this.city = city;
		this.tempLow = tempLow;
		this.tempHigh = tempHigh;
		this.date = date;
	}

	@Column(name = "city", nullable = false, length = 56)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "temp_low", nullable = false)
	public short getTempLow() {
		return this.tempLow;
	}

	public void setTempLow(short tempLow) {
		this.tempLow = tempLow;
	}

	@Column(name = "temp_high", nullable = false)
	public short getTempHigh() {
		return this.tempHigh;
	}

	public void setTempHigh(short tempHigh) {
		this.tempHigh = tempHigh;
	}

	@Column(name = "date", nullable = false, length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TemperatureId))
			return false;
		TemperatureId castOther = (TemperatureId) other;

		return ((this.getCity() == castOther.getCity()) || (this.getCity() != null
				&& castOther.getCity() != null && this.getCity().equals(castOther.getCity())))
				&& (this.getTempLow() == castOther.getTempLow())
				&& (this.getTempHigh() == castOther.getTempHigh())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + this.getTempLow();
		result = 37 * result + this.getTempHigh();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
